include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    unnecessary_new: false
    prefer_single_quotes: false
    curly_braces_in_flow_control_structures: false
    omit_local_variable_types: false
    # - cancel_subscriptions
    # - hash_and_equals
    # - iterable_contains_unrelated_type
    # - list_remove_unrelated_type
    # - prefer_expression_function_bodies
    # - test_types_in_equals
