name: telegram_bot
description: Telegram bot
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  true_core:
    git:
      url: https://github.com/TrueCollaboration/true_core.dart.git
  json_ex:
    git:
      url: https://github.com/TrueCollaboration/json_ex.dart.git
  json_annotation_ex:
    git:
      url: https://github.com/TrueCollaboration/json_annotation_ex.dart.git
      
  dio: any
  either_dart: any
  path: any
  path_provider: any
  tuple: any
  desktop_window: any


# dependency_overrides:
#   true_core:
#     path:  D:\.dev\projects\github\flutter\packages\true_core
#   json_ex:
#     path:  D:\.dev\projects\github\flutter\packages\json_ex
#   json_annotation_ex:
#     path:  D:\.dev\projects\github\flutter\packages\json_annotation_ex

dev_dependencies:
  build_runner: any
  pedantic: ^1.11.1
  # json_serializable_ex:
    # git:
    #   url: https://github.com/TrueCollaboration/json_serializable_ex.git
    # path: D:\.dev\projects\github\flutter\packages\json_serializable_ex